"""Acquire empirical anchor semantics without promoting14meters to wholehome."""
import pandas as pd,numpy as np,collections
from common import *
RAW=OUT/'raw/CN_OBEE/The CN-OBEE dataset'
def main():
 guard();meta=read(OUT/'raw/CN_OBEE_metadata.json');info=meta['files'][0];assert hashlib.md5((OUT/'raw/CN_OBEE.zip').read_bytes()).hexdigest()==info['computed_md5'];power=pd.read_csv(RAW/'Power.csv',index_col='time',parse_dates=True);assert len(power.columns)==14 and power.index.is_unique and power.index.is_monotonic_increasing;delta=power.index.to_series().diff().dropna();assert (delta==pd.Timedelta(minutes=1)).all();n=len(power);channels=[]
 for col in power:
  s=power[col];valid=s.notna();assert np.isfinite(s[valid]).all() and s[valid].min()>=0;channels.append({'channel':col,'rows':n,'valid_minutes':int(valid.sum()),'missing_minutes':int((~valid).sum()),'valid_minute_power_integral_kWh':float(s.iloc[:-1].sum()*60/3.6e6),'max_W':float(s.max()),'median_valid_W':float(s.median()),'terminal_endpoint_not_integrated':True,'annual_energy_if_gaps_unknown':None})
 complete=power.notna().all(axis=1);daily=power.resample('D').agg(['count','sum']);day_index=power.index.normalize();joint=complete.groupby(day_index).agg(['sum','count']);days=joint[(joint['sum']==1440)&(joint['count']==1440)].index;assert len(days)>0;chosen=days[0];sample=power.loc[chosen:chosen+pd.Timedelta(days=1)-pd.Timedelta(minutes=1)];assert len(sample)==1440 and sample.notna().all().all();(OUT/'replay').mkdir(exist_ok=True);sample.to_csv(OUT/'replay/first_complete_power_day.csv',index_label='time')
 room=[];motion=pd.DataFrame(index=power.index)
 for f in sorted(RAW.glob('*.csv')):
  if f.name in ['Power.csv','Outdoor_weather.csv']:continue
  a=pd.read_csv(f,index_col='time',parse_dates=True);assert a.index.equals(power.index);oc=a['occupancy presence (0/1)'];assert set(oc.dropna().unique())<=set([0,1]);motion[f.stem]=oc
  room.append({'file':f.name,'rows':len(a),'sha256':sha(f),'columns':list(a.columns),'missing_by_column':{k:int(a[k].isna().sum()) for k in a},'motion1_is_detection_not_number_of_people':True,'motion0_not_proven_absence':True})
 mvalid=motion.notna().all(axis=1);simultaneous=motion.sum(axis=1,min_count=6);over=int(((simultaneous>3)&mvalid).sum());all0=int(((simultaneous==0)&mvalid).sum());weather=pd.read_csv(RAW/'Outdoor_weather.csv',index_col='time',parse_dates=True);assert weather.index.is_unique and (weather.index.to_series().diff().dropna()==pd.Timedelta(hours=1)).all();out={k:int(weather[k].isna().sum()) for k in weather}
 save(OUT/'CN_OBEE_EMPIRICAL_ADMISSION.json',{'primary_dataset_DOI':meta['doi'],'article_DOI':'10.1038/s41597-023-02891-9','article_year':2024,'observed_households':1,'reported_family_users':3,'census2020_resident_count_H5':None,'published_apartment_area_m2':172.73,'published_duplex_and_height_m':3,'source_license':meta['license'],'ZIP_sha256':sha(OUT/'raw/CN_OBEE.zip'),'ZIP_MD5_verified':True,'time_zone':'UTC+08 from original article;CSVnaive clocks preserved','rows':n,'source_article_nominal365days_vs_actual366days_plus_endpoint':True,'original_rows_preserved_not_silently_truncated':True,'first_time':str(power.index[0]),'last_time':str(power.index[-1]),'power_units':'W per paperTable3/metadata,notkW','channels':channels,'joint_all14_valid_minutes':int(complete.sum()),'joint_all14_complete_days':len(days),'first_complete_replay_day':str(chosen.date()),'first_complete_day_perchannel_kWh':{k:float(sample[k].sum()/60000) for k in sample},'replay_day_sha256':sha(OUT/'replay/first_complete_power_day.csv'),'room_records':room,'motion_over3_minutes':over,'motion_all0_minutes':all0,'motion_valid_minutes':int(mvalid.sum()),'motion_unknown_count_never_as_exact_roster':True,'outdoor_rows':len(weather),'weather_missing':out,'outdoor_pressure_unit':'hPa;convertx100forPa ifused','indoor_pressure_unit':'Pa','PPC_wind_direction_categorical_not_numeric0':True,'all14_sum_scope':'sum of monitoreddevices only;lighting/gas/otherunmetered loads not identified','observed_total_wholehome_energy':None,'national_2020_transport_or_actual_control_willingness_identified':False,'new_family_simulation_prediction_validated':False})
 print({'observed_homes':1,'rows':n,'channels':14,'complete_days':len(days),'first_complete_day':str(chosen.date()),'motion_over3_minutes':over,'motion0_not_absence':all0},flush=True)
if __name__=='__main__':main()
