"""1000 fully specified conditional role/task packets,not observedlifeworlds.
Public pre-event simulated state is an input;post-event energy/temperature
labels stay private. Field origins and unknown acquisition requirements are
explicit. Blank future participant answers must never be auto-completed.
"""
import sqlite3,collections
from common import *
UNKNOWN=['实际完整设备品牌、数量、安装和控制接口','真实日常作息、谁通常在家及任务优先级','身体负荷、行动能力、照护和个体热舒适要求','实际门窗/楼层/施工/管路及燃气和热水服务','真实电表、共用空间电费及控制权','真实收入、偏好、真实参与意愿']
REL={'partner_or_spouse_of':'伴侣或配偶','child_of':'子女','parent_of':'父母','grandchild_of':'孙辈','grandparent_of':'祖辈','sibling_of':'兄弟姐妹','child_partner_of':'子女的伴侣','parent_of_partner_of':'伴侣的父母'}
def prestate(sql,roomids):
 db=sqlite3.connect(sql);a=db.execute('SELECT d.KeyValue,d.Name,r.Value FROM ReportData r JOIN ReportDataDictionary d USING(ReportDataDictionaryIndex) JOIN Time t USING(TimeIndex) WHERE COALESCE(t.WarmupFlag,0)=0 AND t.Month=7 AND t.Day=20 AND t.Hour=19 AND t.Minute=0 AND d.Name IN("Zone Mean Air Temperature","Zone Air Relative Humidity") AND d.ReportingFrequency="Zone Timestep"').fetchall();db.close();return [{'reference_room_id':k.lower(),'variable':n,'value':v,'origin':'physical_simulation_before_intervention','time_metric':'19点前15分钟模型时步平均'} for k,n,v in a if k in [x.upper() for x in roomids]]
def main():
 guard();profiles={x['slot_id']:x for x in read(V7/'HOUSEHOLDS1000_JOINT_GEOMETRY_CANDIDATE.json')['profiles']};oldroles={x['household_id']:x for x in read(V11/'ROLE_PACKET_BINDINGS1000.json')['records']};occupied={x['household_id']:x for x in read(V11/'OCCUPIED_REFERENCE_BINDINGS1000.json')['records']};historic={x['household_id']:x for x in read(V9/'DEVICE_PRIOR_ROUTES1000.json')['routes']};models={x['household_id']:x for x in read(OUT/'BACKGROUND_MODEL_BINDINGS1000.json')['records']};base={x['household_id']:x for x in read(OUT/'BACKGROUND_RUNTIME1000.json')['runs']};tb={x['household_id']:x for x in read(OUT/'THERMAL_PAIR_BINDINGS1000.json')['records']};tp={x['household_id']:x for x in read(OUT/'THERMAL_PAIR_RESULTS1000.json')['pairs']}
 for f in ['role_packages','public_cards','private_labels','questionnaires','provenance_ledgers']:(OUT/f).mkdir(exist_ok=True)
 bindings=[];fields=collections.Counter();worldrefs={x['household_id']:x for x in read(V10/'SERVICE_PORT_BINDINGS.json')['records']}
 for hid,profile in profiles.items():
  old=read(V11/oldroles[hid]['packet_path']);facts=old['public_role_material']['facts'];r=models[hid];task=tb[hid];members=profile['family']['members'];ref=profile['family']['reference_member_id'];idx={m['member_id']:'m'+str(i+1).zfill(2) for i,m in enumerate(members)}
  facts={**facts,'public_members':[{'local_member_id':idx[m['member_id']],'age_reference':m['age_years'],'sex_reference':m['sex'],'generation_level':m['generation_level']} for m in members],
   'public_relations':[{'subject':idx[x['subject']],'type':x['type'],'object':idx[x['object']]} for x in profile['family']['ego_relationships']],'reference_representative':idx[ref]}
  facts.pop('members');facts.pop('member_relations');facts.pop('reference_household_adult_candidates');facts.pop('role_representative_member_id');facts['named_ports_in_separate_prior_component_scenarios']=facts.pop('physical_reference_device_instances');facts['prior_component_ports_are_not_extra_devices_added_to_current_aggregate_model']=True
  state=prestate(OUT/base[hid]['SQL_path'],task['private_reference_rooms']);assert len(state)==2*len(task['private_reference_rooms'])
  given={'reference_day':'典型天气下的7月20日参考实验，不是住户历史的一天','event_window':'19:00–20:00','all_frozen_members_quiet_present':'18:00–22:00固定参考成员位于已分配房间；这次在场是实验条件','private_reference_rooms':task['private_reference_rooms'],'temperature_control':'参考房间上限26°C，提议在19–20点暂改28°C，20点恢复26°C；下限18°C','humidity_boundary':'理想参考调节30%–60%；实际设备能力未知','operator_local_member_id':idx[task['operator_member_id']] if task['enabled'] else None,'control_permission':'本实验给予指定成年成员对本人户独用参考房间的控制许可；真实权限未观察' if task['enabled'] else '参考成员无成年人，手动动作未启用；协助者没有给出','lighting_and_plugs':'全居住单元有声明过的照明和一般设备聚合背景，具体电器不从聚合功率倒推','reference_thermal_conditioner':'理想热负荷边界，输出热需求；具体空调用电没有给出','pre_event_model_state':state,'sharing_and_meter':'共用房间的模型电量单列未分摊；面积分摊不代表实际电费分摊'}
  given['member_room_bindings']=[{'local_member_id':idx[x['member_id']],'reference_room_id':x['room_id']} for x in occupied[hid]['members']]
  source_rooms=read(V10/worldrefs[hid]['service_world_path'])['world']['rooms'];display_names={}
  for room in source_rooms:
   rid=room['room_id'];kind=room['census_room_class'];label='卧室兼起居室' if rid=='combined_bed_living' else '本户房间'+rid.split('_')[-1] if kind=='bedroom' and hid in room['using_household_ids'] else '起居厅' if kind=='living' or 'hall' in rid else '过道' if kind=='corridor' else '厨用空间' if kind=='kitchen' else '卫生/辅助服务空间';display_names[rid]=label
  given['room_display_names']={k:v for k,v in display_names.items() if k in task['private_reference_rooms']};given['private_reference_room_information']=[{'reference_room_id':x['room_id'],'display_name':display_names[x['room_id']],'thermal_floor_area_reference_m2':x['input_floor_area_m2'],'actual_usable_floor_area_not_inferred_from_thermal_reference':True} for x in r['components'] if x['energy_scope_bucket']=='target_private_reference']
  proposal='在已给参考条件下，你是否愿意把独用参考房间的温控上限从26°C改为28°C一小时？可接受、拒绝、修改或要求澄清。' if task['enabled'] else '本角色没有成年人，手动温控动作未启用。请说明制定方案还需明确哪些协助者、权限和服务条件；不要自动增加家庭成员。'
  ledger=[{'field':'population_frame,N,G,members,H6,H7','origin':'statistically_constrained_synthetic','source':str((V7/'HOUSEHOLDS1000_JOINT_GEOMETRY_CANDIDATE.json').relative_to(BASE)),'source_sha256':sha(V7/'HOUSEHOLDS1000_JOINT_GEOMETRY_CANDIDATE.json'),'boundary':'censusmarginal+CHFSproxy joint;not observed targethousehold'},
   {'field':'housing_facets','origin':'official_marginal_reference_assignment','source':str((V9/'PRODUCTION_REFERENCE1000.json').relative_to(BASE)),'boundary':'not observed fullstockjoint'},
   {'field':'historical_reported_device_classes_bins','origin':'matched_auxiliary_report2012','source':str((V9/'DEVICE_PRIOR_ROUTES1000.json').relative_to(BASE)),'matched_route':historic[hid]['match_route'],'boundary':'not2020 currentownership;blank notabsence'},
   {'field':'geometry,rooms,usingrights,partialnamedports','origin':'declared_reference_design_with_traced_sources','source':str((V10/'SERVICE_PORT_BINDINGS.json').relative_to(BASE)),'boundary':'not actualasbuilt or registeredownership'},
   {'field':'lighting_aggregateplug_densities','origin':'published_residential_archetype_reference_adapted','source':'raw/Ding_Zhou2020.pdfp6Table1','source_sha256':sha(OUT/'raw/Ding_Zhou2020.pdf'),'boundary':'Wuhanreference,notnationalstock;aggregate exclusive of separately namedtestports'},
   {'field':'presence,quietphysiology,idealtemperature/humidity/airflow','origin':'experimentally_stipulated','source':r['IDF_path'],'source_sha256':r['IDF_sha256'],'boundary':'not observed diary,agespecificmetabolism,actualhardware or fullcomfort'},
   {'field':'pre_event_air_state','origin':'physical_simulation_before_intervention','source':base[hid]['SQL_path'],'source_sha256':base[hid]['SQL_sha256'],'boundary':'timestepaverage,not measured/instantaneoustruth'},
   {'field':'post_event_thermal_model_labels','origin':'physical_simulation','source':'private_labels/'+hid+'.json','boundary':'thermalkWh not electricity/humanacceptance'},
   {'field':'fullinventory,lifeworld,realmetering,preferences,humananswers','origin':'not_identified_or_not_yet_observed','value':None,'handling':'unknown/request additionalcontext;do not substitute absence or assumedconsent'}]
  public={'role_facts':facts,'given_reference_context':given,'task_id':hid+'_thermal_reference','task_type':'thermal_reference_preference' if task['enabled'] else 'assistance_information_elicitation','proposal':proposal,'unknown_information':UNKNOWN,'instruction':'按给定角色与情景表达判断。已给事实、参考实验设定和你的价值判断分开；未知可以直接回答未知。热需求与用电不同，模型不替你决定愿意或不愿意。'}
  questionnaire={'task_id':public['task_id'],'role_id':hid,'public_material_path':'public_cards/'+hid+'.md','questions':[{'id':'q_n','type':'integer','prompt':'参考家庭固定成员有几人？','purpose':'理解已给事实'},{'id':'q_area','type':'choice','choices':['普查建筑面积参考','净使用面积实测','没有给面积'],'prompt':'所给H6面积是什么口径？'},{'id':'q_origin','type':'choice','choices':['参考场景的实验设定','已经观察到的日常作息','真实接受意愿'],'prompt':'18–22点在场与温控条件属于哪类信息？'},{'id':'decision','type':'choice','choices':['accept','reject','modify','need_clarification','unknown'],'prompt':'你的判断是什么？'},{'id':'reasons','type':'text','prompt':'请说明判断理由，并区分角色事实、给定条件与你的价值判断。'},{'id':'information_needed','type':'text','prompt':'还有哪些未知信息会影响你的判断？'},{'id':'modified_plan','type':'text','prompt':'如果希望修改，请写出时间、房间/设备、动作、操作者、服务约束和仍需澄清的条件。'}],
   'answer_template':{k:None for k in ['actor_id','q_n','q_area','q_origin','decision','reasons','information_needed','modified_plan']},'human_record_status':'not_collected','source_of_future_answer':'realparticipant_submission_requires_provenancereview','physics_and_behavior_labels_separate':True}
  private={'household_id':hid,'model_labels':tp[hid],'comprehension_key':{'q_n':len(members),'q_area':'普查建筑面积参考','q_origin':'参考场景的实验设定'},'decision_has_no_prefilled_correct_answer':True,'actor_preference':None,'human_comprehension_review':None,'human_answer':None,'post_modified_plan_physics_recheck_required':True}
  packet={'household_id':hid,'public':public,'questionnaire_path':'questionnaires/'+hid+'.json','private_labels_path':'private_labels/'+hid+'.json','provenance_path':'provenance_ledgers/'+hid+'.json','reference_context_and_task_schema_complete':True,'complete_actual_lifeworld':False,'human_review_complete':False,'human_answers':None,'collection_release':False,'training_release':False}
  for folder,data in [('role_packages',packet),('private_labels',private),('questionnaires',questionnaire),('provenance_ledgers',{'household_id':hid,'fields':ledger,'historical_assets':historic[hid]['auxiliary_reported_assets'],'current_observed_fullinventory':None})]:save(OUT/folder/(hid+'.json'),data)
  membertext='；'.join(x['local_member_id']+'，'+str(x['age_reference'])+'岁，'+{'male':'男','female':'女'}.get(x['sex_reference'],'性别未指定') for x in facts['public_members']);relationtext='；'.join(x['subject']+'是'+x['object']+'的'+REL[x['type']] for x in facts['public_relations']) or '单人参考家庭';st='；'.join(display_names[s['reference_room_id']]+':'+('温度' if 'Temperature' in s['variable'] else '相对湿度')+f"{s['value']:.2f}"+('°C' if 'Temperature' in s['variable'] else '%') for s in state)
  text='# 参考角色与任务 '+hid+'\n\n城市普通住宅家庭户的合成参考角色，排除镇/乡村/集体/非普通住所。人口和住房边际受约束，完整真实家庭状态未观察。\n\n'+f"所在省份{facts['province']}；固定{facts['resident_count']}人、{facts['generation_count']}代；H6建筑面积参考{facts['H6_building_area_reference_m2']}m²，H7独立自然间{facts['H7_independent_natural_rooms_reference']}间。代表成员{facts['reference_representative']}。\n\n成员："+membertext+'。\n\n'+facts['kitchen_reference']+'；'+facts['toilet_reference']+'。\n\n给定条件：'+given['all_frozen_members_quiet_present']+'；'+given['temperature_control']+'；'+given['control_permission']+'。\n\n干预前模型状态（19点前15分钟平均）：'+st+'。\n\n'+given['lighting_and_plugs']+'。'+given['reference_thermal_conditioner']+'。'+given['sharing_and_meter']+'。\n\n任务：'+proposal+'\n\n未提供的信息：'+'；'.join(UNKNOWN)+'。\n\n'+public['instruction']+'\n'
  placementtext='；'.join(x['local_member_id']+'位于'+display_names[x['reference_room_id']] for x in given['member_room_bindings']);text=text.replace('。\n\n'+facts['kitchen_reference'],'。\n\n成员关系：'+relationtext+'。未声明的成员间完整血缘与姻亲细节保持未知。\n\n参考在场位置：'+placementtext+'。\n\n'+facts['kitchen_reference']);text=text.replace('人口和住房边际受约束，完整真实家庭状态未观察。','家庭角色和本次条件由研究者给定，未提供的信息可说明需要补充。').replace('干预前模型状态（19点前15分钟平均）','19点前参考室内条件（模型15分钟平均）').replace(given['lighting_and_plugs']+'。'+given['reference_thermal_conditioner'],'具体设备清单尚未提供。本次给定温度维持条件，没有提供耗电降幅或费用节省');card=OUT/'public_cards'/(hid+'.md');card.write_text(text);bindings.append({'household_id':hid,'packet_path':'role_packages/'+hid+'.json','packet_sha256':sha(OUT/'role_packages'/(hid+'.json')),'card_path':str(card.relative_to(OUT)),'card_sha256':sha(card),'questionnaire_path':packet['questionnaire_path'],'questionnaire_sha256':sha(OUT/packet['questionnaire_path']),'private_labels_path':packet['private_labels_path'],'private_labels_sha256':sha(OUT/packet['private_labels_path']),'provenance_path':packet['provenance_path'],'provenance_sha256':sha(OUT/packet['provenance_path']),'task_type':public['task_type'],'source_baseline_IDF':r['IDF_path'],'source_baseline_SQL':base[hid]['SQL_path'],'formal_human_answers':0})
  for l in ledger:fields[l['origin']]+=1
 save(OUT/'COLLECTION_BINDINGS1000.json',{'records':bindings,'role_context_task_packets':1000,'thermal_reference_preference_episodes':sum(r['task_type']=='thermal_reference_preference' for r in bindings),'assistance_elicitation_episodes':sum(r['task_type']=='assistance_information_elicitation' for r in bindings),'field_origin_records':dict(fields),'human_reviews':0,'formal_human_answers':0,'collection_release':False,'training_release':False})
 print({'packets':1000,'questions':7000,'formal_answers':0,'provenance_records':9000},flush=True)
if __name__=='__main__':main()
