"""Full field accounting,not guessed completeinstalledinventories."""
import collections
from common import *
def main():
 guard();historical={r['household_id']:r for r in read(V9/'DEVICE_PRIOR_ROUTES1000.json')['routes']};ports={r['household_id']:r for r in read(V10/'SERVICE_PORT_BINDINGS.json')['records']};models=read(OUT/'BACKGROUND_MODEL_BINDINGS1000.json')['records'];rows=[];kinds=collections.Counter()
 for m in models:
  hid=m['household_id'];h=historical[hid];w=read(V10/ports[hid]['service_world_path']);assets=h['auxiliary_reported_assets'];specific=w['service_model']['instantiated_reference_ports']
  for a in assets:kinds[a['class']]+=1
  rows.append({'household_id':hid,'matched2012_asset_reports':assets,'historical_match_route':h['match_route'],'historical_assets_not_current_observed_fullinventory':True,'named_experimental_component_ports_in_separate_V10_V11_worlds':specific,
   'current_background_model_accounting':{'lighting':'one source-backed reference power component perdeclaredroom','general_plugs':'one inclusive aggregate perroom;not inferred TV/fridge/washercounts','controlled_heat':'ideal calorimeter,not owned ACinstallation','specific_port_doublecount':'named appliances removed from this aggregate model;their separate V11tasklabels retained','fuel_DHW_unknown_not_simulated_zero_as_fact':True},
   'background_input':m['IDF_path'],'background_input_sha256':m['IDF_sha256'],'complete_current_realdevice_inventory':None,'realdevice_brands_programs_ages_andpermissions':None,'real_diary':None,'real_sharedmeter_allocation':None,
   'synthetic_design_and_source_observation_fields_separate':True})
 save(OUT/'DEVICE_FIELD_LEDGER1000.json',{'records':rows,'households':1000,'historical_positive_class_report_counts':dict(kinds),'unknown_current_device_count_orabsence_never_filled0':True,'source_supported_port_identity_not_observed_hardware_identity':True})
 intake={'purpose':'future real paired household evidence,distinct from assigned-role answers;currently blank','source_observation_id':None,'linked_synthetic_role_id':None,'automatic_link_to_role_or_replacement_of_frozen_N_G_H6_H7':False,
  'eligibility_and_population':{'observation_date':None,'city_urban_rural_censusclassification_code':None,'code111_112_evidence':None,'household_kind_family_or_collective':None,'residence_kind_H5_ordinary_or_other':None,'province':None,'resident_members':None,'usual_residence_duration_and_away_student_rules':None,'generation_count_and_relation_basis':None},
  'housing':{'H6_building_area_m2_and_basis':None,'usable_area_m2':None,'external_common_area_share_m2':None,'H7_natural_rooms_and_counting_basis':None,'room_functions_dimensions_links':None,'actual_unit_floor_and_building_storeys':None,'neighbour_roof_ground_exposure':None,'window_wall_glazing_andorientation':None,'kitchen_use_andexternalusers':None,'toilet_bathing_water_fuel_services':None},
  'hardware_and_services':{'all_energy_devices_counts_andunknowns':None,'device_identity_rated_Q_vs_total_electric_P_andcurves':None,'dimension_installation_airflow_clearance':None,'control_functions_interfaces_and_holder_permissions':None,'cooking_hotwater_draw_temperature_volume_anddeadline':None,'fixture_supply_drainage_andgas_conditions':None},
  'joint_time_and_measurements':{'real_local_timestamps_andtimezone':None,'occupancy_personcount_vs_motion_proxy':None,'temperature_RH_windows_andweather':None,'wholehome_meter_andsubmeter_boundary':None,'meter_units_frequency_timestamp_interval_convention':None,'missingdata_andmeasurement_provenance':None,'baseline_andintervention_samehousehold_records':None,'actual_executed_action_andservice_constraints':None},
  'human_observation':{'consent_to_data_collection_metadata_ifapplicable':None,'genuine_response_role_vs_realhousehold':None,'trial_comprehension_andquestionnaire_review':None},
  'validation_design':'calibration andheldout validation onindependent times/households;singleCNOBEE household cannotidentify nationaltransport','blank_template_not_collected_record':True}
 save(OUT/'PAIRED_OBSERVATION_INTAKE_TEMPLATE.json',intake);save(OUT/'PARTICIPANT_ANSWER_SCHEMA.json',{'schema':'assigned_role_response_unreviewed_v12','required':['role_id','task_id','material_sha256','actor_id','timestamp_UTC','preview_or_pilot','answers'],'decisions':['accept','reject','modify','need_clarification','unknown'],'origin_claim_not_verified_human_identity':True,'verified_human_provenance_required_beforeformaladmission':True,'no_prefilled_decision_or_fabricated_review':True,'newfacts_inreasons_require_source_or_conditional_tag':True,'modifiedplan_requiresnewphysics_check_not_original_B_label':True,'training_release':False})
 print({'inventory_field_ledgers':1000,'observed_current_fullinventories':0,'paired_source_intake_template':True},flush=True)
if __name__=='__main__':main()
