#!/usr/bin/env python3
"""Build traceable household-building experiments and run real annual EP witnesses."""
import argparse
import copy
import csv
import json
import math
import re
import shutil
import sqlite3
import subprocess
import time
from collections import Counter
from concurrent.futures import ThreadPoolExecutor,as_completed
from pathlib import Path
from household_model import HERE,REPO,BATCH,sha,digest,save,decision,input_errors,make_layout,layout_checks
from idf_builder import build_idf,idf_checks
from weather_rules import resolve_weather

PROTOTYPES=REPO/'docs/research/long-horizon-plan/execution/prelaunch_rigor_20260924/household_300_resolution_20260925/v2_trial_20260926/C_idf/building_300.json'
ENGINE=Path('/Applications/EnergyPlus-24-1-0/energyplus')
SEVERITY=re.compile(r'\*\*\s*(Warning|Severe|Fatal)\s*\*\*',re.I)

def designed_site(station_id):
    c=json.loads((REPO/'simulation_resources/catalog.json').read_text())
    e=next(x for x in c['weather'] if x['id']==station_id)
    loc=next(csv.reader((REPO/e['epw']).open()))
    return {**{k:e[k] for k in ['province','city','latitude','longitude','timezone']},
        'altitude_m':float(loc[9]),'coordinate_evidence':{'status':'designed_site_equal_weather_station',
        'station_id':station_id,'source_catalog_sha256':sha(REPO/'simulation_resources/catalog.json'),
        'reason':'controlled engineering experiment, not city-household sampling'}}

def example_inputs():
    templates=json.loads(PROTOTYPES.read_text())['records']
    template=next(r for r in templates if 'Chengdu' in r['source_catalog_key'] and r['source_branch']=='verified_DeST_90zone_apartment')
    prototype_id=template['role_id'];site=designed_site('chn_561870')
    inputs=[]
    for n,g,rooms,area in [(1,1,1,50),(2,1,2,80),(3,2,2,90),(5,3,3,140),(7,3,4,180),(10,4,5,230)]:
        members=[f'm{i:02d}' for i in range(1,n+1)];groups=[[] for _ in range(rooms)]
        for i,m in enumerate(members):groups[i%rooms].append(m)
        inputs.append({'case_id':f'design_n{n}_g{g}_h7{rooms}','purpose':'prespecified size-room capacity validation, not population sample',
            'family':{'population_scope':'city_family_household','resident_count':n,'resident_member_ids':members,'generation_count_design':g,
                'residence_evidence':'declared_synthetic_role','member_semantics':'resident identifiers only; ages/full kinship/behavior not generated by this stage'},
            'housing':{'H5_status':'ordinary_declared_or_matched','H5_evidence':'declared_design_for_conditional_template_test',
                'occupancy_scope':'whole_household_private','household_storeys':1,'dwelling_type':'apartment',
                'H6_building_area_m2':area,'H6_evidence':'declared_design','H7_natural_rooms_exact':rooms,
                'H7_evidence':'declared_design','H7_definition':'natural_rooms_excluding_kitchen_toilet_corridor_hall','sleep_groups':groups},
            'site':copy.deepcopy(site),
            'model_policy':{'gross_to_zone_floor_ratio':1/1.33,'net_ratio_evidence':'declared_geometry_bridge',
                'floor_position':'middle','wall_boundaries':{'west':'Adiabatic','east':'Adiabatic','south':'Outdoors','north':'Outdoors'},
                'north_axis_deg':0,'air_exchange_ach':.5,'prototype_key':prototype_id},
            'operation_mode':'building_shell_validation','source_provenance':{'status':'fully_declared_research_input','raw_survey_household_copied':False},
            'expected_result':'idf_ready'})
    reference=inputs[2]
    for label,key,value in [('net_ratio_0p8','gross_to_zone_floor_ratio',.8),('top_floor','floor_position','top'),
                           ('orientation_90','north_axis_deg',90),('air_exchange_0p8','air_exchange_ach',.8),
                           ('four_exterior_faces','wall_boundaries',dict.fromkeys(['west','east','south','north'],'Outdoors'))]:
        x=copy.deepcopy(reference);x['case_id']='paired_'+label;x['purpose']='single-factor conditional-model sensitivity'
        x['paired_reference']=reference['case_id'];x['factor_path']='model_policy.'+key;x['model_policy'][key]=value
        inputs.append(x)
    for label,station in [('cold_weather','chn_507740'),('warm_weather','chn_594930')]:
        x=copy.deepcopy(reference);x['case_id']='paired_'+label;x['purpose']='climate stress test of fixed Chengdu prototype, not a matched local stock home'
        x['paired_reference']=reference['case_id'];x['factor_path']='site';x['site']=designed_site(station)
        x['template_transport_evidence']='explicit_climate_stress_experiment_not_local_stock_match'
        inputs.append(x)
    negatives=[
        ('unknown_H5','housing.H5_status','unknown'),
        ('missing_H5_evidence','housing.H5_evidence',None),
        ('shared_scope','housing.occupancy_scope','shared_unknown'),
        ('multistorey','housing.household_storeys',2),
        ('boolean_storeys','housing.household_storeys',True),
        ('unknown_H6','housing.H6_building_area_m2',None),
        ('topcoded_H7','housing.H7_natural_rooms_exact',None),
        ('roster_mismatch','family.resident_count',4),
        ('missing_city','site.city',None),
        ('wrong_timezone','site.timezone',9),
        ('town_target','site.city','某镇'),
        ('unknown_floor','model_policy.floor_position',None),
        ('unknown_prototype','model_policy.prototype_key','not_a_prototype')
    ]
    for label,path,value in negatives:
        x=copy.deepcopy(reference);x['case_id']='reject_'+label;x['purpose']='prespecified independent input refusal control'
        obj=x
        parts=path.split('.')
        for part in parts[:-1]:obj=obj[part]
        obj[parts[-1]]=value;x['expected_result']='blocked';inputs.append(x)
    x=copy.deepcopy(inputs[0]);x['case_id']='reject_capacity';x['housing']['H6_building_area_m2']=20;x['expected_result']='blocked';inputs.append(x)
    x=copy.deepcopy(reference);x['case_id']='reject_shanghai_weather';x['site']=designed_site('shanghai');x['expected_result']='blocked'
    inputs.append(x)
    return inputs

def build_one(item,out,templates):
    safe_id=item.get('case_id') if isinstance(item.get('case_id'),str) and re.fullmatch(r'[A-Za-z0-9_-]{1,100}',item['case_id']) else 'invalid-case-'+digest(item)[:12]
    folder=out/'cases'/safe_id;folder.mkdir(parents=True)
    save(folder/'INPUT.json',item);trace=[]
    for key,obj in [('family',item.get('family')),('housing',item.get('housing')),('site',item.get('site')),('model_policy',item.get('model_policy'))]:
        decision(trace,'input_'+key,obj,'declared_input',['INPUT.json:'+key],'freeze provided fields and evidence; never resample to pass')
    record={'case_id':item.get('case_id'),'case_folder':safe_id,'expected_result':item.get('expected_result'),'input_sha256':sha(folder/'INPUT.json'),
        'experiment_id':BATCH+'__'+out.name,
        'input_semantic_sha256':digest(item),'input_scope':'declared research household-building conditional experiment',
        'status':'blocked','stage_reached':'input_admission','errors':[],'complete_actor_role':False,
        'ordinary_1000_slots_assigned':False,'collection_release':False,'training_release':False}
    errors=input_errors(item)
    if not errors:
        weather=resolve_weather(item.get('site',{}),REPO);save(folder/'WEATHER_MATCH.json',weather)
        if weather['selected'] is None:errors=['weather:'+weather['status']]
        else:
            selected=weather['selected']
            w={'epw_path':selected['epw_absolute_path'],'epw_sha256':selected['epw_sha256'],'location':selected['epw_location']}
            decision(trace,'weather_binding',{'station':selected['id'],'epw_sha256':w['epw_sha256']},'matched_weather_candidate',
                ['input_site','simulation_resources/catalog.json'],'same city and explicit geographic/full-year file policy',
                ['typical-year input, not observed household weather','climate equivalence not certified'])
            record['stage_reached']='template_admission'
            prototype=templates.get(item['model_policy']['prototype_key'])
            if prototype is None:errors=['thermal_prototype_not_in_locked_catalog']
            else:
                # Source template is explicit; no unseen similarity score or
                # first feasible larger-floorplan fallback.
                layout,errors=make_layout(item,trace)
                if layout:
                    save(folder/'LAYOUT.json',layout);record['stage_reached']='geometry_validation'
                    checks=layout_checks(item,layout);save(folder/'LAYOUT_CHECK.json',{'errors':checks})
                    errors+=checks
                if not errors:
                    try:
                        body,ledger,index=build_idf(item,layout,prototype,w,trace)
                        idf=folder/'building.idf';idf.write_text(body)
                        static=idf_checks(body,layout);save(folder/'IDF_STATIC_CHECK.json',static)
                        save(folder/'ASSEMBLY_BINDING.json',ledger);save(folder/'IDF_OBJECT_LINEAGE.json',index)
                        save(folder/'OPERATIONAL_BINDING_INTERFACE.json',{'member_sleep_zone':{m:s['name'] for s in layout['spaces'] for m in s.get('member_ids_sleeping',[])},
                            'allowed_zone_names':[s['name'] for s in layout['spaces']],
                            'people_gains':None,'appliance_inventory_and_power':None,'device_access_control':None,'occupancy_schedules':None,'HVAC_and_controls':None,
                            'status':'pending_explicit_operational_attachment','zero_operational_load_is_not_a_household_observation':True,
                            'next_stage_must_preserve_INPUT_family_and_housing_hashes':True})
                        errors+=static['errors']
                        record.update(stage_reached='IDF_static_validation',idf_path=str(idf),idf_sha256=sha(idf),
                            weather_epw_path=w['epw_path'],weather_epw_sha256=w['epw_sha256'],
                            family_semantic_sha256=digest(item['family']),housing_semantic_sha256=digest(item['housing']),
                            layout_sha256=sha(folder/'LAYOUT.json'),zone_count=static['zone_count'],
                            zone_floor_area_m2=static['zone_floor_area_m2'],natural_room_count=static['H7_from_layout_semantics'],
                            H6_building_area_m2=item['housing']['H6_building_area_m2'])
                        if not errors:record['status']='idf_ready'
                    except (ValueError,AssertionError,KeyError,IndexError) as exc:
                        errors.append('IDF_binding_error:'+str(exc))
    record['errors']=sorted(set(errors));record['trace_sha256']=digest(trace)
    save(folder/'DECISION_TRACE.json',{'batch_id':BATCH,'decisions':trace,'input_preserved_on_failure':True})
    save(folder/'STATUS.json',record)
    return record

def runtime_one(record,out,engine_info):
    started=time.monotonic();folder=out/'runtime'/record['case_id'];folder.mkdir(parents=True)
    command=[str(ENGINE),'-w',record['weather_epw_path'],'-d',str(folder),record['idf_path']]
    result={'case_id':record['case_id'],'input_idf_sha256':record['idf_sha256'],'weather_sha256':record['weather_epw_sha256'],
        'experiment_id':record['experiment_id'],
        'engine':engine_info,'command':command,'scope':'8760-hour annual free-floating thermal-shell witness; no human behavior, occupancy gains or electricity'}
    try:
        proc=subprocess.run(command,capture_output=True,text=True,timeout=240)
        (folder/'process.log').write_text(proc.stdout+'\n'+proc.stderr)
        err=(folder/'eplusout.err').read_text() if (folder/'eplusout.err').exists() else ''
        end=(folder/'eplusout.end').read_text() if (folder/'eplusout.end').exists() else ''
        counts=Counter(m.group(1).lower() for m in SEVERITY.finditer(err))
        errors=[]
        if proc.returncode!=0 or 'EnergyPlus Completed Successfully' not in end:errors.append('engine_not_completed')
        if counts['severe'] or counts['fatal']:errors.append('severe_or_fatal')
        values=[];area=None;hours=0;byzone={};location_rows=[]
        sql=folder/'eplusout.sql'
        if sql.exists():
            db=sqlite3.connect(sql)
            try:
                warm=db.execute('select count(*) from Time where coalesce(WarmupFlag,0)=0 and Interval=60').fetchone()[0]
                hours=warm
                area=db.execute('select sum(FloorArea) from Zones').fetchone()[0]
                rows=db.execute("""select d.KeyValue,min(r.Value),max(r.Value),avg(r.Value),count(*)
                    from ReportData r join ReportDataDictionary d using(ReportDataDictionaryIndex)
                    join Time t using(TimeIndex)
                    where d.Name='Zone Mean Air Temperature' and coalesce(t.WarmupFlag,0)=0
                    group by d.KeyValue""").fetchall()
                byzone={r[0]:{'minimum_C':r[1],'maximum_C':r[2],'mean_C':r[3],'hourly_count':r[4]} for r in rows}
                values=[x for r in rows for x in r[1:4]]
                if len(byzone)!=record['zone_count'] or any(r[4]!=8760 for r in rows):errors.append('temperature_series_count_not_full_annual')
                if any(not isinstance(v,(int,float)) or not math.isfinite(v) for v in values):errors.append('temperature_not_finite')
                if hours!=8760:errors.append('SQL_hour_count_not8760')
                if area is None or abs(area-record['zone_floor_area_m2'])>1e-5:errors.append('SQL_geometry_area_mismatch')
            finally:db.close()
        else:errors.append('SQL_missing')
        eio=folder/'eplusout.eio'
        if eio.exists():location_rows=[line for line in eio.read_text().splitlines() if line.lstrip().startswith('Site:Location,')]
        if not location_rows:errors.append('effective_engine_site_location_not_recorded')
        expected=json.loads((out/'cases'/record['case_id']/'WEATHER_MATCH.json').read_text())['selected']['epw_location']
        location_equal=False
        if location_rows:
            fields=next(csv.reader([location_rows[0]]))
            try:
                # Site:Location, Name, Latitude, Longitude, Time Zone, Elevation.
                actual=list(map(float,fields[2:6]))
                target=[expected[k] for k in ['latitude','longitude','timezone','altitude_m']]
                location_equal=all(abs(a-b)<=.011 for a,b in zip(actual,target))
            except ValueError:pass
        if not location_equal:errors.append('effective_engine_site_location_mismatch')
        result.update(status='pass' if not errors else 'failed',returncode=proc.returncode,
            errors=errors,severity=dict(counts),warning_lines=[line for line in err.splitlines() if re.search(r'\*\*\s*Warning\s*\*\*',line,re.I)],
            SQL_hours=hours,SQL_zone_floor_area_m2=area,zone_temperatures=byzone,
            eio_site_location_rows=location_rows,effective_location_matches_selected_epw=location_equal,
            output_hashes={p.name:sha(p) for p in folder.iterdir() if p.is_file()})
    except subprocess.TimeoutExpired:
        result.update(status='failed',errors=['engine_timeout240s'])
    result['elapsed_seconds']=round(time.monotonic()-started,3)
    save(folder/'RUNTIME_CHECK.json',result)
    return result

def audit_slots(out):
    root=HERE.parent;allocation=json.loads((root/'evidence_contract_20261001/POPULATION_ALLOCATION_CANDIDATE_V2.json').read_text())
    support=json.loads((root/'chfs_census_bridge_20261003/SLOT_BRIDGE_AUDIT.json').read_text())
    assert len(allocation['slots'])==len(support['slots'])==1000
    rows=[]
    for s,b in zip(allocation['slots'],support['slots']):
        assert s['slot_id']==b['slot_id']
        rows.append({**s,'source_route_candidate':b['source_route_candidate'],
            'household_to_IDF_status':'waiting_upstream_household_housing_and_site',
            'required_unassigned_fields':['resident roster/relationship design','H5 ordinary/nonordinary bridge','whole/shared exclusive scope','H6 area and evidence','exact H7 including5+ resolution','sleep groups','dwelling/storey/floor/face policies','target city/coordinates','explicit thermal prototype/transfer policy'],
            'H7_conditional_if_ordinary':b['conditional_census_H7_distribution_if_ordinary_dwelling'],
            'IDF_created':False,'input_family_invented_to_fill_slot':False})
    save(out/'TARGET1000_PREREQUISITE_AUDIT.json',{'allocation_sha256':sha(root/'evidence_contract_20261001/POPULATION_ALLOCATION_CANDIDATE_V2.json'),
        'bridge_sha256':sha(root/'chfs_census_bridge_20261003/SLOT_BRIDGE_AUDIT.json'),'slots':rows,
        'complete_upstream_input_slots':0,'actual_IDF_slots':0,'scope':'population slots have source-support diagnostics but no synthesized household/house/site assigned; example models are independent conditional tests',
        'town_rural_excluded':True,'quotas_changed':False})

def main(args):
    out=args.output.resolve()
    if out.exists():raise RuntimeError('use a new output directory; prior experiments immutable')
    out.mkdir(parents=True)
    (out/'code').mkdir()
    for path in HERE.glob('*.py'):shutil.copy2(path,out/'code'/path.name)
    try:
        def reject_constant(value):raise ValueError('nonfinite_JSON_constant:'+value)
        inputs=json.loads(args.inputs.read_text(),parse_constant=reject_constant) if args.inputs else example_inputs()
        def finite_tree(value):
            if isinstance(value,float) and not math.isfinite(value):raise ValueError('nonfinite_JSON_number_after_parse')
            if isinstance(value,dict):
                for child in value.values():finite_tree(child)
            elif isinstance(value,list):
                for child in value:finite_tree(child)
        finite_tree(inputs)
        if isinstance(inputs,dict):inputs=inputs.get('inputs')
        if not isinstance(inputs,list) or not inputs or not all(isinstance(x,dict) for x in inputs):raise ValueError('inputs_must_be_nonempty_array_of_objects')
        ids=[x.get('case_id') for x in inputs]
        if any(not isinstance(x,str) for x in ids):raise ValueError('all_case_ids_must_be_strings')
        if len(set(ids))!=len(ids):raise ValueError('duplicate_case_ids')
    except (ValueError,TypeError,KeyError) as exc:
        save(out/'ADMISSION_FAILURE.json',{'status':'blocked','errors':[str(exc)],'source_input_path':str(args.inputs) if args.inputs else None,
            'source_input_sha256':sha(args.inputs) if args.inputs and args.inputs.exists() else None,'IDFs_written':0})
        return
    templates={r['role_id']:r for r in json.loads(PROTOTYPES.read_text())['records']}
    save(out/'EXPERIMENT_INPUTS.json',inputs)
    save(out/'INPUT_LOCK.json',{'batch_id':BATCH,'prototype_catalog_path':str(PROTOTYPES),'prototype_catalog_sha256':sha(PROTOTYPES),
        'experiment_id':BATCH+'__'+out.name,
        'resource_catalog_path':str(REPO/'simulation_resources/catalog.json'),'resource_catalog_sha256':sha(REPO/'simulation_resources/catalog.json'),
        'code':{p.name:sha(p) for p in (out/'code').glob('*.py')},'seed':None,
        'random_sampling_used':False,'examples_population_representative':False})
    records=[]
    for item in inputs:
        record=build_one(item,out,templates);records.append(record)
        print(json.dumps({'case':record['case_id'],'status':record['status'],'errors':record['errors']},ensure_ascii=False),flush=True)
    audit_slots(out)
    runtime=[]
    if args.runtime:
        version=subprocess.run([str(ENGINE),'--version'],capture_output=True,text=True,check=True).stdout.strip()
        engine_info={'path':str(ENGINE),'version':version,'sha256':sha(ENGINE),'IDD_sha256':sha(ENGINE.parent/'Energy+.idd')}
        accepted=[r for r in records if r['status']=='idf_ready']
        with ThreadPoolExecutor(max_workers=2) as pool:
            tasks=[pool.submit(runtime_one,r,out,engine_info) for r in accepted]
            for task in as_completed(tasks):
                r=task.result();runtime.append(r)
                print(json.dumps({'runtime_case':r['case_id'],'status':r['status'],'errors':r['errors'],'hours':r.get('SQL_hours')},ensure_ascii=False),flush=True)
    save(out/'SUMMARY.json',{'batch_id':BATCH,'scope':'implemented household-to-building-IDF conditional research pipeline, not new1000 actor dataset',
        'experiment_id':BATCH+'__'+out.name,
        'case_count':len(records),'IDF_ready':sum(r['status']=='idf_ready' for r in records),'blocked':sum(r['status']=='blocked' for r in records),
        'expected_status_all_matched':all(r['status']==r['expected_result'] for r in records),
        'actual_EP_annual_runs':len(runtime),'EP_annual_pass':sum(r['status']=='pass' for r in runtime),
        'records':records,'runtime':sorted(runtime,key=lambda x:x['case_id']),
        'population_slots_preserved':1000,'new1000_complete_roles':0,'new1000_IDFs':0,
        'empirical_calibration':False,'collection_release':False,'training_release':False})
    save(out/'MANIFEST.json',{'batch_id':BATCH,'files':{str(p.relative_to(out)):sha(p) for p in out.rglob('*') if p.is_file()},
        'experiment_id':BATCH+'__'+out.name,
        'source_geometry_observed':False,'source_survey_household_copied':False,'collection_release':False})
    print(json.dumps({k:v for k,v in json.loads((out/'SUMMARY.json').read_text()).items() if k not in ['records','runtime']},ensure_ascii=False),flush=True)

if __name__=='__main__':
    ap=argparse.ArgumentParser();ap.add_argument('--output',type=Path,required=True)
    ap.add_argument('--inputs',type=Path);ap.add_argument('--runtime',action='store_true')
    main(ap.parse_args())
